apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cert-alert.fullname" . }}
  labels:
    {{- include "cert-alert.labels" . | nindent 4 }}
spec:
  jobTemplate:
    metadata:
      name: {{ include "cert-alert.fullname" . }}
      labels:
        {{- include "cert-alert.labels" . | nindent 8 }}
    spec:
      backoffLimit: 1
      completions: 1
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
              - configMapRef:
                  name: {{ include "cert-alert.fullname" . }}
              - secretRef:
                  name: {{ include "cert-alert.fullname" . }}
              - secretRef:
                  name: {{ .Values.secret.externalName }}
                  optional: true
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: Never
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  schedule: {{ quote .Values.schedule }}
  concurrencyPolicy: Replace
