{{- if .Values.slackToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-alert.fullname" . }}
  labels:
    {{- include "cert-alert.labels" . | nindent 4 }}
type: Opaque
data:
  slack-token: {{ .Values.slackToken | b64enc }}
{{- end }}