apiVersion: v1
kind: Secret
metadata:
  name: {{- include "cert-alert.fullname" . }}
  labels:
    {{- include "cert-alert.labels" . | nindent 4 }}
stringData:
{{- if .Values.secret.data }}
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
