# Default values for cert-alert.

# Create an app and copy the token here
# See https://github.com/jgreat/cert-alert#setting-up-slack
secret:
  # optional external secret
  externalName: cert-alert
  # Included secret data.
  data:
    # SLACK_TOKEN: ""

configMap:
  data:
    # Alert x days before cert expires. cert-manager waits until 30 days before expiration.
    RENEW_BEFORE: "10"
    # comma separated of hostnames to check
    SUBJECT: ""
    # IP:PORT to check instead of DNS name
    # If you set this all hostnames under SUBJECTS will use this address.
    ADDRESS: ""
    # Slack Description - Use to identify the subject/address source.
    SLACK_DESCRIPTION: ""

schedule: "@daily"

podAnnotations: {}

image:
  repository: jgreat/cert-alert
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
