name: Build cert-alert

on:
  repository_dispatch: {}
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Env
      run: |
        export VERSION=$(echo $GITHUB_REF | cut -d / -f 3)
        echo "::set-env name=VERSION::$VERSION"
        mkdir -p build/package
        cp -R ./chart ./build
        sed -i "s/%VERSION%/$VERSION/g" ./build/chart/Chart.yaml
        curl -f -H 'Cache-Control: max-age=0,no-cache' "http://charts.jgreat.me/index.yaml" -o ./build/old-index.yaml

    - name: Build and Publish Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jgreat/cert-alert
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: VERSION
        buildoptions: --ulimit memlock=-1
        tags: ${{ env.VERSION }},latest

    - name: Package Chart
      uses: WyriHaximus/github-action-helm3@master
      with:
        exec: helm package -d ./build/package ./build/chart

    - name: Create Index
      uses: WyriHaximus/github-action-helm3@master
      with:
        exec: helm repo index --url https://charts.jgreat.me --merge ./build/old-index.yaml ./build/package

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-2
        SOURCE_DIR: ./build/package
