name: Build cert-alert

on:
  repository_dispatch: {}
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Env
      run: |
        echo "::set-env name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)"

    - name: Build and Publish Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jgreat/cert-alert
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: VERSION
        buildoptions: --ulimit memlock=-1
        tags: ${{ env.VERSION }},latest
